### PR TITLE
issue-48: upgraded to latest Buffalo version

### PR DESCRIPTION
**Pull request by briandowns**

### CODE REVIEW

**Comment by markbates** [comment]
You probably want to update the deps buffalo has. I know that pop, soda, and gentronics, at the very least have changed.

**Comment by briandowns** [comment]
Good call. Thanks.

**Comment by briandowns** [comment]
Actually, the way the glide file is, we're good.  Now to understand by werker failed. Who can give me access or let me know what's going on?

**Comment by bketelsen** [comment]
wercker was added by me (by mistake)  I removed it.

**Pull request merged**
