### PR TITLE
issue-9: added sponsor model and test

### PR DESCRIPTION
**Pull request by briandowns**

### CODE REVIEW

**Comment by markbates** [comment]
@briandowns no migrations?

**Comment by markbates** [comment]
Running `soda g model ....` should also generate the migrationsfor you.

**Comment by briandowns** [comment]
I'm apparently too eager... :/  Stand by.

**Comment by markbates** [comment]
We probably also don't need `Contacts in front of some of those fields.

**Comment by markbates** [comment]
Also are all of the fields required, or can some be null? @bketelsen

**Comment by briandowns** [comment]
Do we want a contact type as well?

**Comment by markbates** [comment]
@briandowns probably hotels have contact info as wel.

**Comment by bketelsen** [comment]
LGTM pending codeclimate/govet fixes

**Review by markbates — APPROVED** [review]

**Comment by markbates** [comment]
Yay! Merged!

**Comment by briandowns** [comment]
Thanks for the guidance.

**Pull request merged**
