### PR TITLE
Adding docker-compose to the project.

### PR DESCRIPTION
**Pull request by webRat**
I believe this resolves issue #5 

This adds:

- docker-compose to the project
  - spins up postgres:latest
  - adds new user
  - adds database `gcon_development`
- Fixed README.md

### CODE REVIEW

**Comment by briandowns** [comment]
@juicemia is working on this and a few other components. Not sure if this duplicates any of that or adds.

**Comment by webRat** [comment]
@juicemia should work faster. :P

**Comment by juicemia** [comment]
I have had all this since a couple of days ago. I'm currently working on getting the dev environment running in compose as well. It builds but the live reload doesn't work. @webRat maybe you can solve that issue as well? My branch in my fork is called automate-db. You can use that code to start off.

**Comment by webRat** [comment]
@juicemia I submitted a PR on your branch elsewhere. Not saying that's the fix, but at first glance, that's what I would fix.

Secondly, I'm not sure the live reload will work. I did a lot of research into this. FSNotify doesn't really like being in a docker container and having to listen to external file system changes. At the very least, I couldn't get it to recognize sub-sub directory file saves. That's why I ended up with a `post-save` trigger in my projects that work that you've seen. That work was open sourced here ( https://github.com/WreckingBallStudioLabs/SelfCompilingExample ).

The nice thing about `post-save` triggers is that you can not only apply it to your agnostic IDE, but you can apply it to git hooks as well.

At the very least, you should submit your database changes so that people can at the very least, take advantage of your `docker-compose` progress. 

I'm not actually partaking in this project, I was just trying to do @charliegriefer a favor and simplify some stuff for him in this project. Sorry for stepping on toes.

**Comment by juicemia** [comment]
@webRat don't worry bro. You're not stepping on toes. This stuff needs to get done, doesn't matter who does it. 

I had a similar hunch. Thanks for sharing what you know. I think I'm gonna just submit the PR and move on.

**Pull request closed without merging**
